### ISSUE TITLE
animate loading logo

### ISSUE THREAD

**Issue by markFalcone** [GroupAlert/LifeLine#8]

**Comment by BallisticBall** [comment]
Completed ECG animated gif and uploaded it to UI/UX branch. Check it out and let me know if it jives. https://github.com/GroupAlert/LifeLine/blob/master/LifeLine%20Assets/LL-Animated-Icon.gif

**Comment by pv-gitjob** [comment]
I like it, but could we have that ECG line only in the "L"s and more frequent, and a transparent background.

**Comment by BallisticBall** [comment]
Made the edits. https://github.com/GroupAlert/LifeLine/blob/master/LifeLine%20Assets/LL-Animated-Icon-02.gif

**Comment by markFalcone** [comment]
doone
